import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'antd/dist/reset.css';
import { ReduxProvider } from "@/lib/store/ReduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SWD Frontend Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            width: '100vw',
            height: '100vh',
            background: 'linear-gradient(120deg, #6EDA78, #FFA200)',
            zIndex: -1, 
          }}
        />

        <ReduxProvider>
          {children}
        </ReduxProvider>
        
      </body>
    </html>
  );
}